'use strict';
const test=require('node:test'); const assert=require('node:assert/strict'); const os=require('os'); const path=require('path'); const fs=require('fs');
const {ContextDB}=require('../src/db'); const {compileContext}=require('../src/compiler');
function temp(){const f=path.join(os.tmpdir(),`sctx-${Date.now()}-${Math.random()}.sqlite`);return f;}
function setup(){const f=temp();const db=new ContextDB(f);return{db,f,cleanup(){try{db.db.close()}catch{};for(const s of ['', '-wal','-shm'])fs.rmSync(f+s,{force:true});}}}
function grantRW(db,p){for(const cap of ['read:training','write:training'])db.grant({principal:p,source:'context:s-master',cap,ttl_seconds:3600},'human:owner');}
test('selective compile returns canonical slice only',()=>{const x=setup();try{grantRW(x.db,'agent:writer');const b=compileContext(x.db,{citation:'@context/s-master#training',max_tokens:1000},'agent:writer');assert.equal(b.context.canonical.text.includes('canonical'),true);assert.equal(b.context.canonical.tasks,undefined);}finally{x.cleanup();}});
test('agent cannot approve own draft',()=>{const x=setup();try{grantRW(x.db,'agent:writer');x.db.grant({principal:'human:reviewer',source:'context:s-master',cap:'approve:training',ttl_seconds:3600},'human:owner');const d=x.db.createDraft({contextId:'s-master',section:'training',value:{text:'x'}},'agent:writer');assert.throws(()=>x.db.approveDraft(d.id,'agent:writer'),/separation_of_duties/);const out=x.db.approveDraft(d.id,'human:reviewer');assert.equal(out.canonicalVersion,2);}finally{x.cleanup();}});
test('live claims preserve conflicts and provenance',()=>{const x=setup();try{grantRW(x.db,'agent:writer');x.db.registerSource({id:'a',caps:['read'],reliability:.8},'human:owner');x.db.registerSource({id:'b',caps:['read'],reliability:.9},'human:owner');for(const [source,value] of [['a',1],['b',2]])x.db.ingestClaim({source,entity_id:'e:shared',native_id:'n',context_id:'s-master',section:'training',attr:'status',value,ttl_seconds:300},'human:owner');const b=compileContext(x.db,{citation:'@context/s-master#training',max_tokens:2000},'agent:writer');assert.equal(b.freshness.status,'conflict');assert.equal(b.conflicts.length,1);assert.equal(b.provenance.length,2);}finally{x.cleanup();}});
test('capability grants enforce constraints and max uses',()=>{const x=setup();try{const g=x.db.grant({principal:'agent:p',source:'linkedin',cap:'post:create',constraints:{account:'seif'},ttl_seconds:3600,max_uses:1},'human:owner');const a=x.db.recordAction({source:'linkedin',cap:'post:create',args:{account:'seif'},status:'accepted'},'agent:p');assert.equal(a.grantId,g.id);assert.throws(()=>x.db.recordAction({source:'linkedin',cap:'post:create',args:{account:'seif'}},'agent:p'),/no_active_grant/);}finally{x.cleanup();}});
test('audit chain verifies after writes',()=>{const x=setup();try{x.db.registerSource({id:'weather'},'human:owner');assert.equal(x.db.verifyAudit().ok,true);}finally{x.cleanup();}});
